[package]
name = "osm-history-animation"
version = "0.1.0"
authors = ["Rory McCann <rory@technomancy.org>"]

[dependencies]
osmio = { path = "../osmio/" }
image = "0.12"
gif = { path = "../image-gif/" }
clap = "2"
