[package]
name = "osm-history-animation"
version = "0.1.0"
authors = ["Rory McCann <rory@technomancy.org>"]

[dependencies]
osmio = { git = "https://github.com/rory/osmio" }
image = "0.12"
gif = { git = "https://github.com/rory/image-gif" }
clap = "2"
